sudo: false
language: C
os:
  - linux
  - osx

script:
  - scripts/get.sh __local__
  - xmake lua versioninfo
  - xmake -P core
  - export XMAKE_PROGRAM_DIR=$PWD/xmake
  - core/build/xmake lua versioninfo
