sudo: required
language: C

matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5

env:
  global:
    - LUAROCKS=2.2.2
    - LUA=lua5.1

before_install:
  - rm install
  - source scripts/.travis/setenv_lua.sh
  - luarocks install luacov

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install dmd rust; fi

script:
  - scripts/get.sh __local__
  - xmake lua versioninfo
  - xmake f -m coverage -P core
  - xmake -P core
  - export XMAKE_PROGRAM_DIR=$PWD/xmake
  - core/build/xmake lua versioninfo
  - echo "require('luacov.runner').init({['statsfile']='$PWD/luacov.stats.out',['reportfile']='$PWD/luacov.report.out'})" > tmp
  - cat xmake/core/_xmake_main.lua >> tmp
  - mv tmp xmake/core/_xmake_main.lua
  - cp core/build/xmake $(which xmake) || sudo cp core/build/xmake $(which xmake)
  - xmake lua versioninfo
  - xmake lua --backtrace tests/test.lua

after_success:
  - luacov
  - bash <(curl -s https://codecov.io/bash)
