os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

build_script:
  - ps: Invoke-Expression (Get-Content scripts\get.ps1 | Out-String)
  - cmd: xmake lua versioninfo
  - cmd: if %platform%==Win64 xmake f -a x64 -P core
  - cmd: xmake -P core
  - cmd: set XMAKE_PROGRAM_DIR=%cd%\xmake
  - cmd: core\build\xmake lua versioninfo
