version: v2.1.5.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - ps: Invoke-Webrequest 'http://luarocks.github.io/luarocks/releases/luarocks-2.4.2-win32.zip' -OutFile luarocks.zip
  - ps: Expand-Archive luarocks.zip
  - ps: Copy-Item -Recurse luarocks\luarocks-2.4.2-win32\win32\lua5.1 C:\lua
  - cmd: cd luarocks\luarocks-2.4.2-win32
  - cmd: install.bat /Q
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\LuaRocks;C:\lua\bin
  - cmd: cd ..\..
  - ps: Remove-Item luarocks -Recurse -Force
  - ps: Remove-Item luarocks.zip
  - cmd: luarocks install luacov
  - ps: Copy-Item -Recurse C:\lua\share\lua\5.1 $HOME\xmake\lua

build_script:
  - ps: Invoke-Expression (Get-Content scripts\get.ps1 | Out-String)
  - cmd: xmake lua versioninfo
  - cmd: if %platform%==Win64 xmake f -a x64 -P core
  - cmd: xmake -P core
  - cmd: set XMAKE_PROGRAM_DIR=%cd%\xmake
  - cmd: core\build\xmake lua versioninfo
  - ps: Write-Output "require('luacov.runner').init({['statsfile']='$PWD/luacov.stats.out',['reportfile']='$PWD/luacov.report.out'})".replace('\','/') | Out-File tmp
  - ps: Write-Output (Get-Content xmake\core\_xmake_main.lua | Out-String) | Out-File tmp -Append
  - ps: Invoke-Webrequest 'https://svwh.dl.sourceforge.net/project/dos2unix/dos2unix/7.3.4/dos2unix-7.3.4-win32.zip' -OutFile dos2unix.zip
  - ps: Expand-Archive dos2unix.zip
  - cmd: dos2unix\bin\dos2unix tmp
  - ps: Remove-Item -Recurse dos2unix,dos2unix.zip
  - ps: Move-Item -Force tmp xmake\core\_xmake_main.lua
  - ps: Copy-Item -Force core\build\xmake.exe $HOME\xmake
  - cmd: xmake lua tests\test.lua

on_success:
  - luacov
  - pip install codecov
  - codecov --file luacov.report.out
